In [39]:
# libraries we need
import numpy as np
import cv2
from matplotlib import pyplot as plt

In [47]:
def mask(path='./climbing_app_project/kilter_board_setting.jpeg'):
    # Python program to transform an image using
    # threshold.
    # Image operation using thresholding
    img = cv2.imread(path)

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    ret, thresh = cv2.threshold(gray, 0, 255,
                                cv2.THRESH_BINARY_INV +
                                cv2.THRESH_OTSU)
    
    # Noise removal using Morphological
    # closing operation
    kernel = np.ones((3, 3), np.uint8)
    closing = cv2.morphologyEx(thresh, cv2.MORPH_CLOSE,
                                kernel, iterations = 2)

    # Background area using Dilation
    bg = cv2.dilate(closing, kernel, iterations = 1)

    # Finding foreground area
    dist_transform = cv2.distanceTransform(closing, cv2.DIST_L2, 0)
    ret, fg = cv2.threshold(dist_transform, 0.02
                            * dist_transform.max(), 255, 0)
    # save image
    cv2.imwrite('./climbing_app_project/foreground.jpeg', fg)
    
    # show image
    cv2.imshow('image', fg)
    if cv2.waitKey(0) & 0xFF == ord('q'): 
        cv2.destroyAllWindows()

In [55]:
mask('./climbing_app_project/kilter_board.jpeg')

In [68]:
def contour_recognition(path='./climbing_app_project/foreground.jpeg'):
    # Python code to find the co-ordinates of
    # the contours detected in an image.
    # inputs: path to picture
    # outputs: picture with recognized shapes/contours
    
    # Reading image
    font = cv2.FONT_HERSHEY_COMPLEX
    img2 = cv2.imread(path, cv2.IMREAD_COLOR)

    # Reading same image in another 
    # variable and converting to gray scale.
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)

    # Converting image to a binary image
    # ( black and white only image).
    _, threshold = cv2.threshold(img, 110, 255, cv2.THRESH_BINARY_INV)

    # Detecting contours in image.
    contours, _= cv2.findContours(threshold, cv2.RETR_TREE,
                                   cv2.CHAIN_APPROX_SIMPLE)

    # Going through every contours found in the image.
    for cnt in contours :

        approx = cv2.approxPolyDP(cnt, 0.009 * cv2.arcLength(cnt, True), True)

        # draws boundary of contours.
        cv2.drawContours(img2, [approx], 0, (0, 0, 255), 5) 

        # Used to flatted the array containing
        # the co-ordinates of the vertices.
        n = approx.ravel() 

    # save image
    cv2.imwrite('./climbing_app_project/contours.jpeg', img2)
    
    # Showing the final image.
    cv2.imshow('Contour outlines recognized', img2) 

    # Exiting the window if 'q' is pressed on the keyboard.
    if cv2.waitKey(0) & 0xFF == ord('q'): 
        cv2.destroyAllWindows()
    return contours

In [69]:
contours = contour_recognition()

In [70]:
contours

[array([[[3487, 3018]],
 
        [[3485, 3020]],
 
        [[3485, 3023]],
 
        [[3497, 3023]],
 
        [[3497, 3020]],
 
        [[3495, 3018]]], dtype=int32),
 array([[[3513, 3017]],
 
        [[3511, 3019]],
 
        [[3511, 3023]],
 
        [[3530, 3023]],
 
        [[3530, 3020]],
 
        [[3528, 3018]],
 
        [[3522, 3018]],
 
        [[3521, 3017]]], dtype=int32),
 array([[[  31, 3014]],
 
        [[  30, 3015]],
 
        [[  23, 3015]],
 
        [[  22, 3016]],
 
        [[   9, 3016]],
 
        [[   6, 3019]],
 
        [[   6, 3023]],
 
        [[  51, 3023]],
 
        [[  51, 3019]],
 
        [[  50, 3018]],
 
        [[  50, 3017]],
 
        [[  48, 3015]],
 
        [[  45, 3015]],
 
        [[  44, 3014]]], dtype=int32),
 array([[[ 627, 2993]],
 
        [[ 624, 2996]],
 
        [[ 624, 3002]],
 
        [[ 625, 3003]],
 
        [[ 625, 3004]],
 
        [[ 627, 3006]],
 
        [[ 634, 3006]],
 
        [[ 636, 3004]],
 
        [[ 636, 3003]],
 

if we want to label the stuff for some reason 

In [ ]:
def recognition(path='./climbing_app_project/test_tafel.jpeg'):
    # Python code to find the co-ordinates of
    # the contours detected in an image.
    # inputs: path to picture
    # outputs: picture with recognized shapes/contours
    
    # Reading image
    font = cv2.FONT_HERSHEY_COMPLEX
    img2 = cv2.imread(path, cv2.IMREAD_COLOR)

    # Reading same image in another 
    # variable and converting to gray scale.
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)

    # Converting image to a binary image
    # ( black and white only image).
    _, threshold = cv2.threshold(img, 110, 255, cv2.THRESH_BINARY)

    # Detecting contours in image.
    contours, _= cv2.findContours(threshold, cv2.RETR_TREE,
                                   cv2.CHAIN_APPROX_SIMPLE)

    # Going through every contours found in the image.
    for cnt in contours :

        approx = cv2.approxPolyDP(cnt, 0.009 * cv2.arcLength(cnt, True), True)

        # draws boundary of contours.
        cv2.drawContours(img2, [approx], 0, (0, 0, 255), 5) 

        # Used to flatted the array containing
        # the co-ordinates of the vertices.
        n = approx.ravel() 
        i = 0

        for j in n :
            if(i % 2 == 0):
                x = n[i]
                y = n[i + 1]

                # String containing the co-ordinates.
                string = str(x) + " " + str(y) 

                if(i == 0):
                    # text on topmost co-ordinate.
                    cv2.putText(img2, "Arrow tip", (x, y),
                                    font, 0.5, (255, 0, 0)) 
                else:
                    # text on remaining co-ordinates.
                    cv2.putText(img2, string, (x, y), 
                              font, 0.5, (0, 255, 0)) 
            i = i + 1

    # Showing the final image.
    cv2.imshow('Contour outlines recognized', img2) 

    # Exiting the window if 'q' is pressed on the keyboard.
    if cv2.waitKey(0) & 0xFF == ord('q'): 
        cv2.destroyAllWindows()